# Generated by Django 4.2.8 on 2023-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='post.jpg', null=True, upload_to='post_picture'),
        ),
    ]
