# Generated by Django 4.2.8 on 2023-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='post.jpg', null=True, upload_to='post_picture/'),
        ),
    ]
